-- 코드를 입력하세요
# 멤버ID별 리뷰 개수 -> 리뷰 최대인 멤버 -> 그 멤버의 리뷰 
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW as RR
INNER JOIN MEMBER_PROFILE as MP
ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID =
(
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT