-- 코드를 입력하세요
SELECT PRODUCT_CODE, PRICE * amount as SALES
FROM PRODUCT
LEFT JOIN 
(
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) as amount
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) as OFFLINE_SALE
USING (PRODUCT_ID)
ORDER BY SALES DESC, PRODUCT_CODE