-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK
JOIN
(
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
) AS B
ON BOOK.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY